### ISSUE TITLE
Duplicate entry in gui

### ISSUE THREAD

**Issue by atouminet** [DucNg/fip-player#7]
In some cases, a radio entry will duplicate on the gui.

Input sequence to produce the bug (in vim notation):
```
/contemp<CR><CR><Esc>j<CR>/rock<CR>
```
Which shows

![Screenshot from 2022-12-19 15-19-17](https://user-images.githubusercontent.com/26742167/208446345-02ef6b69-d1f0-480b-af43-9f4c17cbb00d.png)

**Comment by DucNg** [comment]
Thanks for reporting this!

I think this happens because ids in the list change when filtering. Selecting the item from the filtered view actually updates the wrong item because the id is not the good one (when doing `m.list.SetItem(m.playingItemIndex, previousItem)`). It causes the wrong item to get updated with infos from the item you've just selected. No idea on how to fix this for the moment. Needs some thinking 🧠

**Comment by DucNg** [comment]
@atouminet I attempted to fix the issue on this [PR](https://github.com/DucNg/fip-player/pull/16) can you test?
